Fix git hook by correctly checking pushed files

diff --git a/hooks/pre-receive b/hooks/pre-receive
--- a/hooks/pre-receive
+++ b/hooks/pre-receive
@@ -1,27 +1,53 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 
-if git --work-tree=/deploy --git-dir=/app.git checkout -b master; then
-  echo 'Initializing first setup of application!'
-else
-  git --work-tree=/deploy --git-dir=/app.git checkout -f master
-fi
+REPO=$PWD
 
-set -a
-. /set_env_vars.sh
-set +a
+check_files_in () {
+  rev=$1
 
-docker build -f /deploy/Dockerfile -t app /deploy
-tag_hash=`< /dev/urandom tr -dc a-z-0-9 | head -c10`
-APPLICATION_TAG=gcr.io/$PROJECT_ID/vestibulando:$tag_hash
-LATEST_TAG=gcr.io/$PROJECT_ID/vestibulando:latest
+  # create a temporary working directory
+  workdir=$(mktemp -d gitXXXXXX)
+  (
+    # arrange to clean up the workding directory
+    # when the subshell exits
+    trap "cd /; rm -rf $workdir" EXIT
 
-docker tag vestibulando $APPLICATION_TAG
-docker tag vestibulando $LATEST_TAG
-docker login -u _json_key -p "$CONTAINER_REGISTRY_SA" https://gcr.io
-docker push $APPLICATION_TAG
-docker push $LATEST_TAG
-echo "$GKE_SA" > /keyconfig.json
-/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /keyconfig.json --project $PROJECT_ID
-kubectl set image deployment application application=$APPLICATION_TAG
+    # unset GIT_DIR because it would confuse things
+    unset GIT_DIR
+
+    # clone the repository
+    cd $workdir
+    git clone $REPO check
+
+    # checkout the specific revision we're checking
+    cd check
+    git checkout $rev
+
+    # perform some sort of validation.  The exit code of this
+    # command will be the exit code of this function, so
+    # returning an error will reject the push.
+   set -a
+   . /set_env_vars.sh
+   set +a
+
+   docker build -t app .
+   tag_hash=`< /dev/urandom tr -dc a-z-0-9 | head -c10`
+   APPLICATION_TAG=gcr.io/$PROJECT_ID/app:$tag_hash
+   LATEST_TAG=gcr.io/$PROJECT_ID/app:latest
+
+   docker tag app $APPLICATION_TAG
+   docker tag app $LATEST_TAG
+   docker login -u _json_key -p "$CONTAINER_REGISTRY_SA" https://gcr.io
+   docker push $APPLICATION_TAG
+   docker push $LATEST_TAG
+   echo "$GKE_SA" > /keyconfig.json
+   /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /keyconfig.json --project $PROJECT_ID
+   kubectl set image deployment application application=$APPLICATION_TAG
+  )
+}
+
+while read oldrev newrev refname; do
+  check_files_in $newrev || exit 1
+done
